Fix opam error and benchmark dependency
On main,
```
% opam install --deps-only --with-dev-setup .
[WARNING] Failed checks on trace-runtime-events package definition from source at git+file:///Users/nikos/Work/ocaml-trace#main:
  warning 47: Synopsis should start with a capital and not end with a dot
Nothing to do.
```

Plus
```
% dune build
File "bench/dune", line 23, characters 12-21:
23 |  (libraries benchmark trace-fuchsia))
                 ^^^^^^^^^
Error: Library "benchmark" not found.
```

Also, the Github format job fails, because the ocamlformat installed in the container is 0.28.1 whilst the project is on 0.27. In addition, there is no dependency on ocamlformat or a version specification.

Fixes are
- remove final dot from opam package synopsis
- add the `benchmark` dependency behind --with-dev-setup.
- add ocamlformat 0.28.1 as --with-dev-setup dependency and reformat.